### ISSUE TITLE
swim.structure polyglot language bindings

### ISSUE THREAD

**Issue by c9r** [swimos/swim#12]
Flesh out polyglot language bindings for the [**swim-structure** Java library](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.structure). The bindings are located in the [**swim-dynamic-structure** Java library](https://github.com/swimos/swim/tree/master/swim-system-java/swim-polyglot-java/swim.dynamic.structure). The JavaScript bindings should be compatible with the [**@swim/structure** TypeScript library](https://github.com/swimos/swim/tree/master/swim-system-js/swim-core-js/@swim/structure). Make sure to bind static methods, in addition to instance methods.

**Structure bindings**
- [ ] Add `Item` bindings.
- [ ] Add `Field` bindings.
- [ ] Add `Attr` bindings.
- [ ] Add `Slot` bindings.
- [ ] Add `Value` bindings
- [ ] Add `Record` bindings
- [ ] Add `Data` bindings.
- [ ] Add `Text` bindings.
- [ ] Add `Num` bindings.
- [ ] Add `Bool` bindings.
- [ ] Add `Extant` bindings.
- [ ] Add `Absent` bindings.

**Expression bindings**
- [ ] Add `Expression` bindings.
- [ ] Add `Operator` bindings.
- [ ] Add `Selector` bindings.
- [ ] Add `Func` bindings.
- [ ] Add `Interpreter` bindings.

**Form bindings**
- [ ] Add `Form` bindings.

**Comment by freyadyu** [comment]
Hit a question in ItemTypeSpec.java with testing testGetItem(), need your suggestion:

 @Test
  public void testGetItem() {
    try (Context context = Context.create()) {
      final JavaHostRuntime runtime = new JavaHostRuntime();
      final VmBridge bridge = new VmBridge(runtime, "js");
      runtime.addHostLibrary(SwimStructure.LIBRARY);

      final org.graalvm.polyglot.Value bindings = context.getBindings("js");
      bindings.putMember("record", bridge.hostToGuest(
          Record.of(Slot.of("foo", "bar"), Slot.of(Num.from(7877), "number"))));

      assertEquals(bridge.guestToHost(context.eval("js", "record")),
          Record.of(Slot.of("foo", "bar"), Slot.of(Num.from(7877), "number")));
      assertEquals(context.eval("js", "record.getItem(0).stringValue()").asString(), "bar");
      assertEquals(context.eval("js", "record.getItem(0).key.stringValue()").asString(), "foo");
      assertEquals(context.eval("js", "record.getItem(1)"), Slot.of(Num.from(7877), "number"));
    }
  }
------------------------------------------------------------------------------------------------

It throws exception in last assertEqual test, previous three asserEquals tests passed:
java.lang.AssertionError: expected [Slot.of(7877, "number")] but found [swim.vm.VmHostObject@9fd587a7]
        at testng/org.testng.Assert.fail(Assert.java:96)
        at testng/org.testng.Assert.failNotEquals(Assert.java:776)
        at testng/org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at testng/org.testng.Assert.assertEquals(Assert.java:118)
        at testng/org.testng.Assert.assertEquals(Assert.java:442)
        at swim.dynamic.structure/swim.dynamic.structure.ItemTypeSpec.testGetItem(ItemTypeSpec.java:258)

------------------------------------------------------------------------------------------------
Tried different methods to convert "record.getItem(1)" to Record, but didn't find the right method for it. Or are those 2 test cases above it, the right format to test HostItemGetItem()?

**Comment by ajay-gov** [comment]
Item 1 is a Slot. This should work I think but maybe this is not what you want to do?
`assertEquals(context.eval("js", "record.getItem(1).stringValue().asString()"), "number");
 assertEquals(context.eval("js", "record.getItem(1).key.numberValue()").asInt(), 78);`

**Comment by freyadyu** [comment]
Hey Chris,

I committed my code with HostItem.java and ItemTypeSpec.java. I converted all methods in Item.java with corresponding functionalities in Item.ts, but I listed some left over questions I had while developing, we can sync when you in the office. At the meantime, I'll keep working on the rest of the list:

- [ ] In Item.ts, there're only stringValue(), numberValue(), and booleanValue(). But in Item.java, besides those three methods, there're byteValue(), shortValue(), intValue(), longValue(), floatValue(), doubleValue(), integerValue(), charValue(). I added those in HostItem.java, but not sure whether I should keep them there cause there's no corresponding method in Item.ts. 
- [ ] If we want to keep those method in HostItem, I also met a problem while writing test case with integerValue(), need your instruction.

- [ ] Met problem with writing HostLambda test case

- [ ] For HostItemFilter, HostItemEvaluate, HostItemSubstitute, they involved with Selector and Interpreter bindings, need your instruction

- [ ] For HostItemCast, HostItemCoerce, HostItemDisplay, HostItemDebug, HostItemGlobalScope need your instruction for test case

- [ ] For HostItemFromObject test case, I met question with test case that fromObject() takes map as parameter with following error exception: 
      Map<String, String> map = new HashMap<>();
      map.put("foo", "bar");
      bindings.putMember("mapOb", bridge.hostToGuest(Item.fromObject(map)));
      assertEquals(bridge.guestToHost(context.eval("js", "mapOb")), Slot.of("foo", "bar"));

      error:
        swim.dynamic.structure.ItemTypeSpec > testFromObject FAILED
    	java.lang.IllegalArgumentException: {foo=bar}
        	at swim.structure/swim.structure.Value.fromObject(Value.java:1049)
        	at swim.structure/swim.structure.Item.fromObject(Item.java:943)
        	at swim.dynamic.structure/	 
          swim.dynamic.structure.ItemTypeSpec.testFromObject(ItemTypeSpec.java:87)

- [ ]  assertEqual case failed for HostItemToString
