### ISSUE TITLE
swim.deflate tests failing on Windows

### ISSUE THREAD

**Issue by SirCipher** [swimos/swim#20]
The `swim.deflate.DeflateSpec` unit tests are failing on Windows. Possibly due to carriage returns in the files that are being read.

```
swim.deflate.DeflateSpec > deflateLorem FAILED
    org.testng.TestException: swim.codec.EncoderException: truncated
        at swim.deflate.DeflateSpec.assertDeflates(DeflateSpec.java:95)
        at swim.deflate.DeflateSpec.assertDeflates(DeflateSpec.java:117)
        at swim.deflate.DeflateSpec.deflateLorem(DeflateSpec.java:50)

        Caused by:
        swim.codec.EncoderException: truncated
            at swim.deflate.Deflate.pull(Deflate.java:576)
            at swim.deflate.DeflateSpec.assertDeflates(DeflateSpec.java:93)
            ... 2 more

swim.deflate.DeflateSpec > deflateLoremIncrementally FAILED
    org.testng.TestException: swim.codec.EncoderException: truncated
        at swim.deflate.DeflateSpec.assertDeflates(DeflateSpec.java:95)
        at swim.deflate.DeflateSpec.deflateLoremIncrementally(DeflateSpec.java:57)

        Caused by:
        swim.codec.EncoderException: truncated
            at swim.deflate.Deflate.pull(Deflate.java:576)
            at swim.deflate.DeflateSpec.assertDeflates(DeflateSpec.java:93)
            ... 1 more
```

The `InflateSpec` unit tests are also failing:

```
swim.deflate.InflateSpec > inflateLorem FAILED
    java.lang.AssertionError: expected [2585] but found [2576]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:652)
        at org.testng.Assert.assertEquals(Assert.java:662)
        at swim.deflate.InflateSpec.assertInflates(InflateSpec.java:99)
        at swim.deflate.InflateSpec.assertInflates(InflateSpec.java:118)
        at swim.deflate.InflateSpec.inflateLorem(InflateSpec.java:47)

swim.deflate.InflateSpec > inflateLoremIncrementally FAILED
    java.lang.AssertionError: expected [2585] but found [2576]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:652)
        at org.testng.Assert.assertEquals(Assert.java:662)
        at swim.deflate.InflateSpec.assertInflates(InflateSpec.java:99)
        at swim.deflate.InflateSpec.inflateLoremIncrementally(InflateSpec.java:55)
```

**Comment by SirCipher** [comment]
Resolved in https://github.com/swimos/swim-system-java/commit/3d039e1b2bbeac3778d7ea725c6133c453efe63a
