### ISSUE TITLE
swim.server.ListDownlinkSpec failing unit tests

### ISSUE THREAD

**Issue by SirCipher** [swimos/swim#21]
testInsert failing:
---
It appears that in some instances values are not set on the lane and so the latches do not countdown enough.

A working run:
```
Test: 200
link willUpdate index: 0
ListLinkController- link didUpdate index: 0; newValue "a"; oldValue: null
link willUpdate index: 1
ListLinkController- link didUpdate index: 1; newValue "b"; oldValue: null
link willUpdate index: 2
ListLinkController- link didUpdate index: 2; newValue "c"; oldValue: null
ReadOnlyListLinkController- link didUpdate index: 0; newValue "a"; oldValue: ""
ListLinkController- link willReceive body @update(index:0,key:%YEdkLwEr) a
link willUpdate index: 0
ListLinkController- link didUpdate index: 0; newValue "a"; oldValue: ""
ListLinkController- link didReceive body @update(index:0,key:%YEdkLwEr) a
ListLinkController- link willReceive body @update(index:1,key:%wziHqnnF) b
link willUpdate index: 1
ReadOnlyListLinkController- link didUpdate index: 1; newValue "b"; oldValue: ""
ListLinkController- link didUpdate index: 1; newValue "b"; oldValue: ""
ListLinkController- link didReceive body @update(index:1,key:%wziHqnnF) b
ListLinkController- link willReceive body @update(index:2,key:%F2COEsmf) c
link willUpdate index: 2
ListLinkController- link didUpdate index: 2; newValue "c"; oldValue: ""
ReadOnlyListLinkController- link didUpdate index: 2; newValue "c"; oldValue: ""
ListLinkController- link didReceive body @update(index:2,key:%F2COEsmf) c
```

When an error occurs:
```
Test: 201
link willUpdate index: 0
ListLinkController- link didUpdate index: 0; newValue "a"; oldValue: null
link willUpdate index: 1
ListLinkController- link didUpdate index: 1; newValue "b"; oldValue: null
link willUpdate index: 2
ListLinkController- link didUpdate index: 2; newValue "c"; oldValue: null
ListLinkController- link willReceive body @update(index:0,key:%CH1SQHk/) a
link willUpdate index: 0
ListLinkController- link didUpdate index: 0; newValue "a"; oldValue: ""
ListLinkController- link didReceive body @update(index:0,key:%CH1SQHk/) a
ReadOnlyListLinkController- link didUpdate index: 0; newValue "a"; oldValue: ""
ListLinkController- link willReceive body @update(index:1,key:%61kn6Rag) b
link willUpdate index: 1
ListLinkController- link didUpdate index: 1; newValue "b"; oldValue: ""
ListLinkController- link didReceive body @update(index:1,key:%61kn6Rag) b
ListLinkController- link willReceive body @update(index:2,key:%B1KKssj0) c
link willUpdate index: 2
ListLinkController- link didUpdate index: 2; newValue "c"; oldValue: ""
ListLinkController- link didReceive body @update(index:2,key:%B1KKssj0) c
ReadOnlyListLinkController- link didUpdate index: 1; newValue "b"; oldValue: ""
ReadOnlyListLinkController- link didUpdate index: 2; newValue "c"; oldValue: ""
```

testClear failures:
----
```
swim.server.ListDownlinkSpec > testClear FAILED
    java.lang.AssertionError: expected [3] but found [0]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:652)
        at org.testng.Assert.assertEquals(Assert.java:662)
        at swim.server.ListDownlinkSpec.testClear(ListDownlinkSpec.java:681)
```

**Comment by DobromirM** [comment]
The `testInsert` can sometimes add the values before the downlinks are open. This could be fixed using an additional countdown latch that gets released after `onSync` from the downlink has completed.

However, the `didReceive` callback for ListDonwlink seems to be faulty as it is not always called. Will open a new ticket for that.

**Comment by DobromirM** [comment]
Related #26

**Comment by DobromirM** [comment]
#27 Fixes the problems for both `testInsert` and `testClear` and I've changed the implementation of both tests to use an additional `CountDownLatch` to ensure that the downlinks are open before sending messages, instead of the arbitrary waits that were previously in place.

I suggest that we go forward and replace the timeouts in all other unit tests with count down latches.
