### ISSUE TITLE
swim.codec unit tests failing on Windows

### ISSUE THREAD

**Issue by SirCipher** [swimos/swim#23]
A number of the unit tests in the `swim.codec` package are failing on Windows due to carriage returns being present in the `Input`s. This causes equality checks to fail due to mismatched string lengths.

**Comment by SirCipher** [comment]
```
> Task :swim-codec:test FAILED

swim.codec.DiagnosticSpec > testCauseAfterError STANDARD_OUT
    [1;31merror[0m[1m: clobbered field[0m
     [1;34m-->[0m input:2:3
    [1;34m  |[0m
    [1;34m2 |[0m   foo: 1
    [1;34m  |[0m   [1;31m^^^ defined here[0m
    [1;34m.[0m  
    [1;34m4 |[0m   foo: 3
    [1;34m  |[0m   [1;32m^^^ clobbered here[0m

swim.codec.DiagnosticSpec > testCauseAfterError FAILED
    java.lang.AssertionError: expected [error: clobbered field
     --> input:2:3
      |
    2 |   foo: 1
      |   ^^^ defined here
    .  
    4 |   foo: 3
      |   ^^^ clobbered here] but found [error: clobbered field
     --> input:2:3
      |
    2 |   foo: 1
      |   ^^^ defined here
    .  
    4 |   foo: 3
      |   ^^^ clobbered here]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testCauseAfterError(DiagnosticSpec.java:298)

swim.codec.DiagnosticSpec > testCauseBeforeError STANDARD_OUT
    [1;31merror[0m[1m: duplicate field[0m
     [1;34m-->[0m input:4:3
    [1;34m  |[0m
    [1;34m2 |[0m   foo: 1
    [1;34m  |[0m   [1;32m^^^ first use[0m
    [1;34m.[0m  
    [1;34m4 |[0m   foo: 3
    [1;34m  |[0m   [1;31m^^^ second use[0m

swim.codec.DiagnosticSpec > testCauseBeforeError FAILED
    java.lang.AssertionError: expected [error: duplicate field
     --> input:4:3
      |
    2 |   foo: 1
      |   ^^^ first use
    .  
    4 |   foo: 3
      |   ^^^ second use] but found [error: duplicate field
     --> input:4:3
      |
    2 |   foo: 1
      |   ^^^ first use
    .  
    4 |   foo: 3
      |   ^^^ second use]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testCauseBeforeError(DiagnosticSpec.java:276)

swim.codec.DiagnosticSpec > testMultiInputCause STANDARD_OUT
    [1;31merror[0m[1m: ambiguous definition[0m
     [1;34m-->[0m input1:1:1
    [1;34m  |[0m
    [1;34m1 |[0m test: false
    [1;34m  |[0m [1;31m^^^^ duplicate definition[0m
     [1;34m-->[0m input0:1:1
    [1;34m  |[0m
    [1;34m1 |[0m test: true
    [1;34m  |[0m [1;32m^^^^ original definition[0m

swim.codec.DiagnosticSpec > testMultiInputCause FAILED
    java.lang.AssertionError: expected [error: ambiguous definition
     --> input1:1:1
      |
    1 | test: false
      | ^^^^ duplicate definition
     --> input0:1:1
      |
    1 | test: true
      | ^^^^ original definition] but found [error: ambiguous definition
     --> input1:1:1
      |
    1 | test: false
      | ^^^^ duplicate definition
     --> input0:1:1
      |
    1 | test: true
      | ^^^^ original definition]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testMultiInputCause(DiagnosticSpec.java:341)

swim.codec.DiagnosticSpec > testMultiInputMultiMessageCause STANDARD_OUT
    [1;31merror[0m[1m: ambiguous definition[0m
     [1;34m-->[0m input1:1:1
    [1;34m  |[0m
    [1;34m1 |[0m test: false
    [1;34m  |[0m [1;31m^^^^ duplicate definition[0m
    [1;32mnote[0m[1m: clobbered declaration[0m
     [1;34m-->[0m input0:1:1
    [1;34m  |[0m
    [1;34m1 |[0m test: true
    [1;34m  |[0m [1;32m^^^^ original definition[0m

swim.codec.DiagnosticSpec > testMultiInputMultiMessageCause FAILED
    java.lang.AssertionError: expected [error: ambiguous definition
     --> input1:1:1
      |
    1 | test: false
      | ^^^^ duplicate definition
    note: clobbered declaration
     --> input0:1:1
      |
    1 | test: true
      | ^^^^ original definition] but found [error: ambiguous definition
     --> input1:1:1
      |
    1 | test: false
      | ^^^^ duplicate definition
    note: clobbered declaration
     --> input0:1:1
      |
    1 | test: true
      | ^^^^ original definition]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testMultiInputMultiMessageCause(DiagnosticSpec.java:361)

swim.codec.DiagnosticSpec > testMultiMessageCause STANDARD_OUT
    [1;31merror[0m[1m: duplicate field[0m
     [1;34m-->[0m input:4:3
    [1;34m  |[0m
    [1;34m4 |[0m   foo: 3
    [1;34m  |[0m   [1;31m^^^ second use[0m
    [1;32mnote[0m[1m: clobbered field[0m
     [1;34m-->[0m input:2:3
    [1;34m  |[0m
    [1;34m2 |[0m   foo: 1
    [1;34m  |[0m   [1;32m^^^ first use[0m

swim.codec.DiagnosticSpec > testMultiMessageCause FAILED
    java.lang.AssertionError: expected [error: duplicate field
     --> input:4:3
      |
    4 |   foo: 3
      |   ^^^ second use
    note: clobbered field
     --> input:2:3
      |
    2 |   foo: 1
      |   ^^^ first use] but found [error: duplicate field
     --> input:4:3
      |
    4 |   foo: 3
      |   ^^^ second use
    note: clobbered field
     --> input:2:3
      |
    2 |   foo: 1
      |   ^^^ first use]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testMultiMessageCause(DiagnosticSpec.java:320)

swim.codec.DiagnosticSpec > testOneLineMark STANDARD_OUT
     [1;34m-->[0m input:1:6
    [1;34m  |[0m
    [1;34m1 |[0m Hello, world!
    [1;34m  |[0m      [1;36m^[0m

swim.codec.DiagnosticSpec > testOneLineMark FAILED
    java.lang.AssertionError: expected [ --> input:1:6
      |
    1 | Hello, world!
      |      ^] but found [ --> input:1:6
      |
    1 | Hello, world!
      |      ^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineMark(DiagnosticSpec.java:56)

swim.codec.DiagnosticSpec > testOneLineMarkAtNewline STANDARD_OUT
     [1;34m-->[0m input:1:14
    [1;34m  |[0m
    [1;34m1 |[0m Hello, world!
    [1;34m  |[0m              [1;35m^[0m

swim.codec.DiagnosticSpec > testOneLineMarkAtNewline FAILED
    java.lang.AssertionError: expected [ --> input:1:14
      |
    1 | Hello, world!
      |              ^] but found [ --> input:1:14
      |
    1 | Hello, world!
      |              ^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineMarkAtNewline(DiagnosticSpec.java:44)

swim.codec.DiagnosticSpec > testOneLineMarkAtStart STANDARD_OUT
     [1;34m-->[0m input:1:1
    [1;34m  |[0m
    [1;34m1 |[0m Hello, world!
    [1;34m  |[0m [1;35m^[0m

swim.codec.DiagnosticSpec > testOneLineMarkAtStart FAILED
    java.lang.AssertionError: expected [ --> input:1:1
      |
    1 | Hello, world!
      | ^] but found [ --> input:1:1
      |
    1 | Hello, world!
      | ^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineMarkAtStart(DiagnosticSpec.java:32)

swim.codec.DiagnosticSpec > testOneLineMarkNoNewline STANDARD_OUT
     [1;34m-->[0m input:1:6
    [1;34m  |[0m
    [1;34m1 |[0m Hello, world!
    [1;34m  |[0m      [1;33m^[0m

swim.codec.DiagnosticSpec > testOneLineMarkNoNewline FAILED
    java.lang.AssertionError: expected [ --> input:1:6
      |
    1 | Hello, world!
      |      ^] but found [ --> input:1:6
      |
    1 | Hello, world!
      |      ^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineMarkNoNewline(DiagnosticSpec.java:82)

swim.codec.DiagnosticSpec > testOneLineMarkWithNote STANDARD_OUT
     [1;34m-->[0m input:1:6
    [1;34m  |[0m
    [1;34m1 |[0m Hello, world!
    [1;34m  |[0m      [1;32m^ comma[0m
    [1;34m  |[0m
    [1;34m  =[0m [1mnote:[0m optional punctuation

swim.codec.DiagnosticSpec > testOneLineMarkWithNote FAILED
    java.lang.AssertionError: expected [ --> input:1:6
      |
    1 | Hello, world!
      |      ^ comma
      |
      = note: optional punctuation] but found [ --> input:1:6
      |
    1 | Hello, world!
      |      ^ comma
      |
      = note: optional punctuation]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineMarkWithNote(DiagnosticSpec.java:68)

swim.codec.DiagnosticSpec > testOneLineNumberPadding STANDARD_OUT
      [1;34m-->[0m input:10:6
    [1;34m   |[0m
    [1;34m10 |[0m Hello, world!
    [1;34m   |[0m      [1;33m^[0m

swim.codec.DiagnosticSpec > testOneLineNumberPadding FAILED
    java.lang.AssertionError: expected [  --> input:10:6
       |
    10 | Hello, world!
       |      ^] but found [  --> input:10:6
       |
    10 | Hello, world!
       |      ^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineNumberPadding(DiagnosticSpec.java:119)

swim.codec.DiagnosticSpec > testOneLineSpan STANDARD_OUT
     [1;34m-->[0m input:1:8
    [1;34m  |[0m
    [1;34m1 |[0m Hello, wordl!
    [1;34m  |[0m        [1;33m^^^^^[0m

swim.codec.DiagnosticSpec > testOneLineSpan FAILED
    java.lang.AssertionError: expected [ --> input:1:8
      |
    1 | Hello, wordl!
      |        ^^^^^] but found [ --> input:1:8
      |
    1 | Hello, wordl!
      |        ^^^^^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineSpan(DiagnosticSpec.java:94)

swim.codec.DiagnosticSpec > testOneLineSpanWithMessageAndNotes STANDARD_OUT
    [1;33mwarning[0m[1m: check your spelling[0m
     [1;34m-->[0m input:1:8
    [1;34m  |[0m
    [1;34m1 |[0m Hello, wordl!
    [1;34m  |[0m        [1;33m^^^^^ did you mean 'world'?[0m

swim.codec.DiagnosticSpec > testOneLineSpanWithMessageAndNotes FAILED
    java.lang.AssertionError: expected [warning: check your spelling
     --> input:1:8
      |
    1 | Hello, wordl!
      |        ^^^^^ did you mean 'world'?] but found [warning: check your spelling
     --> input:1:8
      |
    1 | Hello, wordl!
      |        ^^^^^ did you mean 'world'?]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testOneLineSpanWithMessageAndNotes(DiagnosticSpec.java:106)

swim.codec.DiagnosticSpec > testSevenLineSpan STANDARD_OUT
     [1;34m-->[0m input:1:7
    [1;34m  |[0m
    [1;34m1 |[0m   @test {
    [1;34m  |[0m  [1;31m_______^[0m
    [1;34m2 |[0m [1;31m|[0m   a: 1
    [1;34m3 |[0m [1;31m|[0m   b: 2
    [1;34m4 |[0m [1;31m|[0m   c: 3
    [1;34m5 |[0m [1;31m|[0m   d: 4
    [1;34m6 |[0m [1;31m|[0m   e: 5
    [1;34m7 |[0m [1;31m|[0m ]
    [1;34m  |[0m [1;31m|_^[0m

swim.codec.DiagnosticSpec > testSevenLineSpan FAILED
    java.lang.AssertionError: expected [ --> input:1:7
      |
    1 |   @test {
      |  _______^
    2 | |   a: 1
    3 | |   b: 2
    4 | |   c: 3
    5 | |   d: 4
    6 | |   e: 5
    7 | | ]
      | |_^] but found [ --> input:1:7
      |
    1 |   @test {
      |  _______^
    2 | |   a: 1
    3 | |   b: 2
    4 | |   c: 3
    5 | |   d: 4
    6 | |   e: 5
    7 | | ]
      | |_^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testSevenLineSpan(DiagnosticSpec.java:170)

swim.codec.DiagnosticSpec > testSevenLineSpanWithNotes STANDARD_OUT
     [1;34m-->[0m input:1:7
    [1;34m  |[0m
    [1;34m1 |[0m   @test {
    [1;34m  |[0m  [1;31m_______^ opened here[0m
    [1;34m2 |[0m [1;31m|[0m   a: 1
    [1;34m3 |[0m [1;31m|[0m   b: 2
    [1;34m4 |[0m [1;31m|[0m   c: 3
    [1;34m5 |[0m [1;31m|[0m   d: 4
    [1;34m6 |[0m [1;31m|[0m   e: 5
    [1;34m7 |[0m [1;31m|[0m ]
    [1;34m  |[0m [1;31m|_^ implicitly closed[0m

swim.codec.DiagnosticSpec > testSevenLineSpanWithNotes FAILED
    java.lang.AssertionError: expected [ --> input:1:7
      |
    1 |   @test {
      |  _______^ opened here
    2 | |   a: 1
    3 | |   b: 2
    4 | |   c: 3
    5 | |   d: 4
    6 | |   e: 5
    7 | | ]
      | |_^ implicitly closed] but found [ --> input:1:7
      |
    1 |   @test {
      |  _______^ opened here
    2 | |   a: 1
    3 | |   b: 2
    4 | |   c: 3
    5 | |   d: 4
    6 | |   e: 5
    7 | | ]
      | |_^ implicitly closed]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testSevenLineSpanWithNotes(DiagnosticSpec.java:195)

swim.codec.DiagnosticSpec > testTenLineSpan STANDARD_OUT
      [1;34m-->[0m input:1:7
    [1;34m   |[0m
     [1;34m1 |[0m   @test {
    [1;34m   |[0m  [1;31m_______^[0m
     [1;34m2 |[0m [1;31m|[0m   a: 1
     [1;34m3 |[0m [1;31m|[0m   b: 2
    [1;34m..[0m   [1;31m|[0m
     [1;34m8 |[0m [1;31m|[0m   g: 7
     [1;34m9 |[0m [1;31m|[0m   h: 8
    [1;34m10 |[0m [1;31m|[0m ]
    [1;34m   |[0m [1;31m|_^[0m

swim.codec.DiagnosticSpec > testTenLineSpan FAILED
    java.lang.AssertionError: expected [  --> input:1:7
       |
     1 |   @test {
       |  _______^
     2 | |   a: 1
     3 | |   b: 2
    ..   |
     8 | |   g: 7
     9 | |   h: 8
    10 | | ]
       | |_^] but found [  --> input:1:7
       |
     1 |   @test {
       |  _______^
     2 | |   a: 1
     3 | |   b: 2
    ..   |
     8 | |   g: 7
     9 | |   h: 8
    10 | | ]
       | |_^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testTenLineSpan(DiagnosticSpec.java:223)

swim.codec.DiagnosticSpec > testTenLineSpanWithNotes STANDARD_OUT
      [1;34m-->[0m input:1:7
    [1;34m   |[0m
     [1;34m1 |[0m   @test {
    [1;34m   |[0m  [1;31m_______^ opened here[0m
     [1;34m2 |[0m [1;31m|[0m   a: 1
     [1;34m3 |[0m [1;31m|[0m   b: 2
    [1;34m..[0m   [1;31m|[0m
     [1;34m8 |[0m [1;31m|[0m   g: 7
     [1;34m9 |[0m [1;31m|[0m   h: 8
    [1;34m10 |[0m [1;31m|[0m ]
    [1;34m   |[0m [1;31m|_^ implicitly closed[0m

swim.codec.DiagnosticSpec > testTenLineSpanWithNotes FAILED
    java.lang.AssertionError: expected [  --> input:1:7
       |
     1 |   @test {
       |  _______^ opened here
     2 | |   a: 1
     3 | |   b: 2
    ..   |
     8 | |   g: 7
     9 | |   h: 8
    10 | | ]
       | |_^ implicitly closed] but found [  --> input:1:7
       |
     1 |   @test {
       |  _______^ opened here
     2 | |   a: 1
     3 | |   b: 2
    ..   |
     8 | |   g: 7
     9 | |   h: 8
    10 | | ]
       | |_^ implicitly closed]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testTenLineSpanWithNotes(DiagnosticSpec.java:251)

swim.codec.DiagnosticSpec > testTwoLineSpan STANDARD_OUT
     [1;34m-->[0m input:1:7
    [1;34m  |[0m
    [1;34m1 |[0m   @test {"
    [1;34m  |[0m  [1;31m_______^[0m
    [1;34m2 |[0m [1;31m|[0m }"
    [1;34m  |[0m [1;31m|__^[0m

swim.codec.DiagnosticSpec > testTwoLineSpan FAILED
    java.lang.AssertionError: expected [ --> input:1:7
      |
    1 |   @test {"
      |  _______^
    2 | | }"
      | |__^] but found [ --> input:1:7
      |
    1 |   @test {"
      |  _______^
    2 | | }"
      | |__^]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testTwoLineSpan(DiagnosticSpec.java:132)

swim.codec.DiagnosticSpec > testTwoLineSpanWithMessageAndNotes STANDARD_OUT
    [1;31merror[0m[1m: unclosed block[0m
     [1;34m-->[0m input:1:7
    [1;34m  |[0m
    [1;34m1 |[0m   @test {"
    [1;34m  |[0m  [1;31m_______^ opened here[0m
    [1;34m2 |[0m [1;31m|[0m }"
    [1;34m  |[0m [1;31m|__^ implicitly closed[0m
    [1;34m  |[0m
    [1;34m  =[0m [1mnote:[0m check delimiter ordering

swim.codec.DiagnosticSpec > testTwoLineSpanWithMessageAndNotes FAILED
    java.lang.AssertionError: expected [error: unclosed block
     --> input:1:7
      |
    1 |   @test {"
      |  _______^ opened here
    2 | | }"
      | |__^ implicitly closed
      |
      = note: check delimiter ordering] but found [error: unclosed block
     --> input:1:7
      |
    1 |   @test {"
      |  _______^ opened here
    2 | | }"
      | |__^ implicitly closed
      |
      = note: check delimiter ordering]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:453)
        at org.testng.Assert.assertEquals(Assert.java:463)
        at swim.codec.DiagnosticSpec.testTwoLineSpanWithMessageAndNotes(DiagnosticSpec.java:147)
```

**Comment by SirCipher** [comment]
A related issue here from URI Path parsing:

```
swim.js.JsAgentSpec > testJsAgentCommands FAILED
    error: unexpected '\\'
     --> :1:3
      |
    1 | D:\a\1\s\swim-polyglot-java\swim.js
      |   ^
        at swim.codec.Parser.error(Parser.java:231)
        at swim.uri.UriParser.parsePathString(UriParser.java:213)
        at swim.uri.UriPath.parse(UriPath.java:573)
        at swim.js.JsAgentSpec.testJsAgentCommands(JsAgentSpec.java:35)
```

**Comment by SirCipher** [comment]
Resolved in https://github.com/swimos/swim-system-java/commit/e84a82752c9044c3965de1b072e6cc47baa08b21 and https://github.com/swimos/swim-system-java/commit/13252cb20c2a0dd6518aba831462fde9a669b5a1
