### ISSUE TITLE
swim.remote.RemoteHostSpec#testRemoteHostCommands didUpgrade not called the correct number of times

### ISSUE THREAD

**Issue by SirCipher** [swimos/swim#28]
As per the title, the `didUpgrade` phase is not called every time during the test. 

```
Gradle suite > Gradle test > swim.remote.RemoteHostSpec > testRemoteHostCommands FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at testng@6.14.3/org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at testng@6.14.3/org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
        at testng@6.14.3/org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
        at testng@6.14.3/org.testng.AssertJUnit.assertEquals(AssertJUnit.java:170)
        at testng@6.14.3/org.testng.AssertJUnit.assertEquals(AssertJUnit.java:177)
        at swim.remote/swim.remote.RemoteHostSpec.testRemoteHostCommands(RemoteHostSpec.java:168)
```

I have tried adding a latch to the `didConnect` of the `RemoteHostClient` used and I noticed that in some cases the phase is called two times and others four. I also observed the following exception at times:

```
error: expected carriage return, but found end of input
 --> :2:16
  |
2 |   |                ^
	at swim.codec/swim.codec.Parser.error(Parser.java:231)
	at swim.http/swim.http.HttpRequestParser.parse(HttpRequestParser.java:173)
	at swim.http/swim.http.HttpRequestParser.feed(HttpRequestParser.java:52)
	at swim.codec/swim.codec.InputParser.parse(InputParser.java:50)
	at swim.codec/swim.codec.InputParser.feed(InputParser.java:31)
	at swim.codec/swim.codec.Parser.feed(Parser.java:144)
	at swim.codec/swim.codec.Parser.feed(Parser.java:101)
	at swim.io/swim.io.IpSocketModem.doRead(IpSocketModem.java:164)
	at swim.io/swim.io.TcpSocket.doRead(TcpSocket.java:230)
	at swim.io/swim.io.StationTransport.doRead(Station.java:579)
	at swim.io/swim.io.StationReader.runTask(Station.java:796)
	at swim.concurrent/swim.concurrent.TheaterTask.run(Theater.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

As well as:
```
swim.io.StationException: Can't restart stopped station
	at swim.io/swim.io.Station.start(Station.java:141)
	at swim.io/swim.io.Station.transport(Station.java:221)
	at swim.io/swim.io.IpStation.connectTcp(IpStation.java:83)
	at swim.remote/swim.remote.RemoteHostClient.connectHttp(RemoteHostClient.java:99)
	at swim.remote/swim.remote.RemoteHostClient.connect(RemoteHostClient.java:84)
	at swim.remote/swim.remote.RemoteHostClient.willOpen(RemoteHostClient.java:138)
	at swim.runtime/swim.runtime.AbstractTierBinding.start(AbstractTierBinding.java:168)
	at swim.remote/swim.remote.RemoteHost.didUpgrade(RemoteHost.java:532)
	at swim.remote/swim.remote.RemoteHostSpec$5.didUpgrade(RemoteHostSpec.java:119)
	at swim.io.warp/swim.io.warp.WarpWebSocket.didUpgrade(WarpWebSocket.java:127)
	at swim.io.ws/swim.io.ws.WsUpgradeRequester.didRespond(WsUpgradeRequester.java:82)
	at swim.io.http/swim.io.http.HttpClientRequester.didRespond(HttpClientRequester.java:150)
	at swim.io.http/swim.io.http.HttpClientModem.didRespond(HttpClientModem.java:345)
	at swim.io.http/swim.io.http.HttpClientModem.didRead(HttpClientModem.java:75)
	at swim.io.http/swim.io.http.HttpClientModem.doReadResponseEntity(HttpClientModem.java:323)
	at swim.io.http/swim.io.http.HttpClientRequester.willRespond(HttpClientRequester.java:145)
	at swim.io.http/swim.io.http.HttpClientModem.willRespond(HttpClientModem.java:336)
	at swim.io.http/swim.io.http.HttpClientModem.didRead(HttpClientModem.java:73)
	at swim.io.http/swim.io.http.HttpClientModem.didRead(HttpClientModem.java:34)
	at swim.io/swim.io.IpSocketModem.doRead(IpSocketModem.java:171)
	at swim.io/swim.io.TcpSocket.doRead(TcpSocket.java:230)
	at swim.io/swim.io.StationTransport.doRead(Station.java:579)
	at swim.io/swim.io.StationReader.runTask(Station.java:796)
	at swim.concurrent/swim.concurrent.TheaterTask.run(Theater.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

and:

```
java.util.NoSuchElementException
	at swim.collections/swim.collections.FingerTrieSeq.head(FingerTrieSeq.java:203)
	at swim.io.http/swim.io.http.HttpServerModem.willRespond(HttpServerModem.java:310)
	at swim.io.http/swim.io.http.HttpServerModem.doWriteResponse(HttpServerModem.java:304)
	at swim.io.http/swim.io.http.HttpServerResponder.doRespond(HttpServerResponder.java:175)
	at swim.io.http/swim.io.http.HttpServerModem.willRequest(HttpServerModem.java:289)
	at swim.io.http/swim.io.http.HttpServerModem.didRead(HttpServerModem.java:71)
	at swim.io.http/swim.io.http.HttpServerModem.didRead(HttpServerModem.java:34)
	at swim.io/swim.io.IpSocketModem.doRead(IpSocketModem.java:171)
	at swim.io/swim.io.TcpSocket.doRead(TcpSocket.java:230)
	at swim.io/swim.io.StationTransport.doRead(Station.java:579)
	at swim.io/swim.io.StationReader.runTask(Station.java:796)
	at swim.concurrent/swim.concurrent.TheaterTask.run(Theater.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
java.util.NoSuchElementException
	at swim.collections/swim.collections.FingerTrieSeq.head(FingerTrieSeq.java:203)
	at swim.io.http/swim.io.http.HttpServerModem.willRespond(HttpServerModem.java:310)
	at swim.io.http/swim.io.http.HttpServerModem.doWriteResponse(HttpServerModem.java:304)
	at swim.io.http/swim.io.http.HttpServerResponder.doRespond(HttpServerResponder.java:175)
	at swim.io.http/swim.io.http.HttpServerModem.willRequest(HttpServerModem.java:289)
	at swim.io.http/swim.io.http.HttpServerModem.didRead(HttpServerModem.java:71)
	at swim.io.http/swim.io.http.HttpServerModem.didRead(HttpServerModem.java:34)
	at swim.io/swim.io.IpSocketModem.doRead(IpSocketModem.java:171)
	at swim.io/swim.io.TcpSocket.doRead(TcpSocket.java:230)
	at swim.io/swim.io.StationTransport.doRead(Station.java:579)
	at swim.io/swim.io.StationReader.runTask(Station.java:796)
	at swim.concurrent/swim.concurrent.TheaterTask.run(Theater.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by SirCipher** [comment]
Another exception thrown from running this test:
```
swim.codec.InputException: invalid step
	at swim.codec/swim.codec.Utf8DecodedInput.step(Utf8DecodedInput.java:332)
	at swim.http/swim.http.HttpRequestParser.parse(HttpRequestParser.java:183)
	at swim.http/swim.http.HttpRequestParser.feed(HttpRequestParser.java:52)
	at swim.codec/swim.codec.InputParser.parse(InputParser.java:50)
	at swim.codec/swim.codec.InputParser.feed(InputParser.java:31)
	at swim.codec/swim.codec.Parser.feed(Parser.java:144)
	at swim.codec/swim.codec.Parser.feed(Parser.java:101)
	at swim.io/swim.io.IpSocketModem.doRead(IpSocketModem.java:164)
	at swim.io/swim.io.TcpSocket.doRead(TcpSocket.java:230)
	at swim.io/swim.io.StationTransport.doRead(Station.java:582)
	at swim.io/swim.io.StationReader.runTask(Station.java:809)
	at swim.concurrent/swim.concurrent.TheaterTask.run(Theater.java:442)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
